import { useState } from "react";
import { useQuery, useQueryClient, useMutation } from "@tanstack/react-query";
import { useServerFn } from "@tanstack/react-start";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { PanelEmpty } from "./panel-empty";
import { listNotes, listMemory } from "@/lib/api";
import {
  generateCards,
  listDueCards,
  listCards,
  reviewCard,
  deleteCard,
  type ReviewCard,
  type ReviewRating,
} from "@/lib/review.functions";
import { Brain, Loader2, Sparkles, Trash2, RotateCcw, BookOpen } from "lucide-react";
import { cn } from "@/lib/utils";
import { toast } from "sonner";

const RATINGS: { key: ReviewRating; label: string; hotkey: string; variant: string }[] = [
  { key: "again", label: "Again", hotkey: "1", variant: "bg-destructive text-destructive-foreground hover:bg-destructive/90" },
  { key: "hard", label: "Hard", hotkey: "2", variant: "bg-warning text-warning-foreground hover:bg-warning/90" },
  { key: "good", label: "Good", hotkey: "3", variant: "bg-secondary text-secondary-foreground hover:bg-secondary/90" },
  { key: "easy", label: "Easy", hotkey: "4", variant: "bg-primary text-primary-foreground hover:bg-primary/90" },
];

export function ReviewPanel({ workspaceId }: { workspaceId: string }) {
  const qc = useQueryClient();
  const generateFn = useServerFn(generateCards);
  const dueFn = useServerFn(listDueCards);
  const cardsFn = useServerFn(listCards);
  const reviewFn = useServerFn(reviewCard);
  const deleteFn = useServerFn(deleteCard);

  const dueKey = ["review-due", workspaceId];
  const allKey = ["review-cards", workspaceId];

  const { data: due = [], isLoading: dueLoading } = useQuery({
    queryKey: dueKey,
    queryFn: () => dueFn({ data: { workspaceId } }),
  });
  const { data: allCards = [], isLoading: cardsLoading } = useQuery({
    queryKey: allKey,
    queryFn: () => cardsFn({ data: { workspaceId } }),
  });
  const { data: notes = [] } = useQuery({
    queryKey: ["notes", workspaceId],
    queryFn: () => listNotes(workspaceId),
  });
  const { data: memories = [] } = useQuery({
    queryKey: ["memory", "workspace", workspaceId],
    queryFn: () => listMemory({ layer: "workspace", workspaceId }),
  });

  const [practicing, setPracticing] = useState(false);

  const generate = useMutation({
    mutationFn: async ({ sourceType, sourceId }: { sourceType: ReviewCard["source_type"]; sourceId: string }) => {
      return generateFn({ data: { sourceType, sourceId } });
    },
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: dueKey });
      qc.invalidateQueries({ queryKey: allKey });
      toast.success("Cards generated");
    },
    onError: (err: Error) => toast.error(err.message),
  });

  const review = useMutation({
    mutationFn: ({ cardId, rating }: { cardId: string; rating: ReviewRating }) =>
      reviewFn({ data: { cardId, rating } }),
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: dueKey });
      qc.invalidateQueries({ queryKey: allKey });
    },
    onError: (err: Error) => toast.error(err.message),
  });

  const remove = useMutation({
    mutationFn: (cardId: string) => deleteFn({ data: { cardId } }),
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: dueKey });
      qc.invalidateQueries({ queryKey: allKey });
      toast.success("Card deleted");
    },
  });

  const hasSources = notes.length > 0 || memories.length > 0;

  return (
    <div className="space-y-6">
      <div className="rounded-2xl border border-border bg-accent/40 p-4 text-sm text-muted-foreground">
        Spaced repetition turns your notes and memory into durable knowledge. Cards due today are
        queued for practice; new cards are generated by AI from any note or memory entry.
      </div>

      {!hasSources && allCards.length === 0 && (
        <PanelEmpty
          icon={BookOpen}
          title="Nothing to review yet"
          body="Add notes or workspace memory first, then generate review cards from them."
        />
      )}

      {practicing ? (
        <PracticeView
          cards={due}
          onRate={(cardId, rating) => {
            void review.mutateAsync({ cardId, rating });
          }}
          onDone={() => setPracticing(false)}
          onDelete={(id) => remove.mutate(id)}
        />
      ) : (
        <>
          <div className="grid gap-4 lg:grid-cols-[1fr_320px]">
            <div className="space-y-4">
              <div className="flex items-center justify-between">
                <h3 className="font-semibold">Due today</h3>
                <Badge variant="secondary">
                  {due.length} {due.length === 1 ? "card" : "cards"}
                </Badge>
              </div>

              {dueLoading ? (
                <Skeleton />
              ) : due.length === 0 ? (
                <div className="rounded-2xl border border-dashed border-border bg-card p-8 text-center">
                  <Brain className="mx-auto h-6 w-6 text-muted-foreground" />
                  <p className="mt-3 text-sm font-medium">All caught up</p>
                  <p className="text-xs text-muted-foreground">No cards are due right now.</p>
                </div>
              ) : (
                <Button onClick={() => setPracticing(true)} className="w-full">
                  <RotateCcw className="mr-2 h-4 w-4" />
                  Practice now
                </Button>
              )}

              <div className="pt-4">
                <div className="mb-3 flex items-center justify-between">
                  <h3 className="font-semibold">All cards</h3>
                  <span className="text-xs text-muted-foreground">{allCards.length} total</span>
                </div>
                {cardsLoading ? (
                  <Skeleton />
                ) : allCards.length === 0 ? (
                  <p className="text-sm text-muted-foreground">Generate cards from a source to get started.</p>
                ) : (
                  <div className="grid gap-2">
                    {allCards.slice(0, 10).map((c) => (
                      <Card key={c.id} className="group">
                        <CardContent className="flex items-start justify-between gap-3 p-3">
                          <div className="min-w-0">
                            <p className="font-medium leading-snug">{c.front}</p>
                            <p className="mt-1 line-clamp-2 text-xs text-muted-foreground">{c.back}</p>
                          </div>
                          <Button
                            variant="ghost"
                            size="icon"
                            className="shrink-0 opacity-0 group-hover:opacity-100"
                            onClick={() => remove.mutate(c.id)}
                            aria-label="Delete card"
                          >
                            <Trash2 className="h-4 w-4 text-destructive" />
                          </Button>
                        </CardContent>
                      </Card>
                    ))}
                  </div>
                )}
              </div>
            </div>

            <div className="space-y-4">
              <h3 className="font-semibold">Generate cards</h3>
              <p className="text-xs text-muted-foreground">
                Pick a source with enough content. AI will extract questions and answers.
              </p>

              <SourceList
                label="Notes"
                items={notes}
                onGenerate={(n) => generate.mutate({ sourceType: "note", sourceId: n.id })}
                loading={generate.isPending}
              />
              <SourceList
                label="Memory"
                items={memories}
                onGenerate={(m) => generate.mutate({ sourceType: "memory", sourceId: m.id })}
                loading={generate.isPending}
              />
            </div>
          </div>
        </>
      )}
    </div>
  );
}

function SourceList<T extends { id: string; title: string }>({
  label,
  items,
  onGenerate,
  loading,
}: {
  label: string;
  items: T[];
  onGenerate: (item: T) => void;
  loading: boolean;
}) {
  if (items.length === 0) return null;
  return (
    <div className="space-y-2">
      <p className="text-xs font-medium uppercase tracking-wide text-muted-foreground">{label}</p>
      <div className="space-y-1">
        {items.map((item) => (
          <div
            key={item.id}
            className="flex items-center justify-between gap-2 rounded-lg border border-border bg-card px-3 py-2"
          >
            <span className="truncate text-sm">{item.title || "Untitled"}</span>
            <Button
              variant="ghost"
              size="sm"
              disabled={loading}
              onClick={() => onGenerate(item)}
              className="h-7 gap-1 px-2 text-xs"
            >
              {loading ? <Loader2 className="h-3 w-3 animate-spin" /> : <Sparkles className="h-3 w-3" />}
              Generate
            </Button>
          </div>
        ))}
      </div>
    </div>
  );
}

function PracticeView({
  cards,
  onRate,
  onDone,
  onDelete,
}: {
  cards: ReviewCard[];
  onRate: (cardId: string, rating: ReviewRating) => void;
  onDone: () => void;
  onDelete: (cardId: string) => void;
}) {
  const [index, setIndex] = useState(0);
  const [flipped, setFlipped] = useState(false);

  if (cards.length === 0 || index >= cards.length) {
    return (
      <div className="rounded-2xl border border-border bg-card p-10 text-center shadow-soft">
        <Brain className="mx-auto h-8 w-8 text-primary" />
        <h3 className="mt-4 text-lg font-semibold">Session complete</h3>
        <p className="mt-1 text-sm text-muted-foreground">Great work. Come back when more cards are due.</p>
        <Button className="mt-5" onClick={onDone}>
          Back to review
        </Button>
      </div>
    );
  }

  const card = cards[index];

  const rate = (rating: ReviewRating) => {
    onRate(card.id, rating);
    setFlipped(false);
    setIndex((i) => i + 1);
  };

  return (
    <div className="mx-auto max-w-2xl space-y-6">
      <div className="flex items-center justify-between text-xs text-muted-foreground">
        <span>
          Card {index + 1} of {cards.length}
        </span>
        <Button variant="ghost" size="sm" onClick={onDone}>
          End session
        </Button>
      </div>

      <button
        onClick={() => setFlipped((f) => !f)}
        className="w-full rounded-3xl border border-border bg-card p-10 text-left shadow-soft transition-all hover:shadow-pop focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"
      >
        <p className="text-xs font-medium uppercase tracking-wide text-muted-foreground">
          {flipped ? "Answer" : "Question"}
        </p>
        <p className={cn("mt-4 text-xl font-medium leading-relaxed", !flipped && "text-2xl")}>
          {flipped ? card.back : card.front}
        </p>
        <p className="mt-6 text-xs text-muted-foreground">Click anywhere to flip</p>
      </button>

      <div className="grid grid-cols-4 gap-2">
        {RATINGS.map((r) => (
          <Button
            key={r.key}
            className={cn("h-14 flex-col gap-0.5", r.variant)}
            onClick={() => rate(r.key)}
            disabled={!flipped}
            title={`Press ${r.hotkey}`}
          >
            <span className="text-sm font-semibold">{r.label}</span>
            <span className="text-[10px] opacity-80">{r.hotkey}</span>
          </Button>
        ))}
      </div>

      <div className="flex justify-center">
        <Button variant="ghost" size="sm" onClick={() => onDelete(card.id)} className="text-destructive">
          <Trash2 className="mr-2 h-4 w-4" /> Delete this card
        </Button>
      </div>
    </div>
  );
}

function Skeleton() {
  return (
    <div className="space-y-2">
      <div className="h-12 animate-pulse rounded-lg bg-muted" />
      <div className="h-12 animate-pulse rounded-lg bg-muted" />
    </div>
  );
}
