CREATE TABLE ai_rate_limits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    endpoint TEXT NOT NULL,
    called_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_ai_rate_limits_user_endpoint_time ON ai_rate_limits(user_id, endpoint, called_at);

CREATE OR REPLACE FUNCTION check_rate_limit(p_user_id UUID, p_endpoint TEXT, p_limit INT, p_window_seconds INT)
RETURNS BOOLEAN
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_count INT;
BEGIN
    -- Delete records older than the window to keep the table clean
    DELETE FROM ai_rate_limits 
    WHERE user_id = p_user_id 
      AND endpoint = p_endpoint 
      AND called_at < NOW() - (p_window_seconds || ' seconds')::interval;

    -- Check current count
    SELECT COUNT(*) INTO v_count
    FROM ai_rate_limits
    WHERE user_id = p_user_id 
      AND endpoint = p_endpoint
      AND called_at >= NOW() - (p_window_seconds || ' seconds')::interval;

    IF v_count >= p_limit THEN
        RETURN FALSE;
    END IF;

    -- Insert new record
    INSERT INTO ai_rate_limits (user_id, endpoint) VALUES (p_user_id, p_endpoint);
    RETURN TRUE;
END;
$$;
